/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Muhammad Asna Faqih
 */
// <editor-fold defaultstate="collapsed" desc="Import">
import java.awt.*;
import java.awt.Image;
import java.sql.*;
import javax.swing.JOptionPane;
import Connection.ConnectionDB;
import Views.FrameMenuPelapor;
import java.io.*;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
// </editor-fold>

public class FrameLaporan extends javax.swing.JFrame {

    /**
     * Creates new form FrameLaporan
     */
    
    // <editor-fold defaultstate="collapsed" desc="Deklarasi Kelas">
    public Connection connect;
    public PreparedStatement statemen = null;
    public Statement statemen2;
    public ResultSet rss;
    public String sql="";
    public FrameLogin lgn;
    public String s;
    public String filename = null;
    public Image image;
    // </editor-fold>
    
    public FrameLaporan() {
        initComponents();
        setTitle("Laporan");
    }
    
    public void tampilData(){
        DefaultTableModel tabelTampil = new DefaultTableModel();
        tabelTampil.addColumn("User_ID");
        tabelTampil.addColumn("Nama_Lengkap");
        tabelTampil.addColumn("No_Identitas");
        tabelTampil.addColumn("Alamat");
        tabelTampil.addColumn("No_Telepon");
        tabelTampil.addColumn("Email");
        tabelTampil.addColumn("Password");
        try{
            String url;
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/karyawan?zeroDateTimeBehavior=convertToNull";
            connect=DriverManager.getConnection(url,"root","");
            sql="SELECT * FROM register order by User_ID asc";
            statemen2=connect.createStatement();
            ResultSet rs= statemen.executeQuery(sql);
            while(rs.next()){
                tabelTampil.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
            });
            }
            TableLaporan.setModel(tabelTampil);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ada kesalahan");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGambar2 = new Views.PanelGambar();
        PanelKerusakanJalan = new javax.swing.JPanel();
        LabelJudul = new javax.swing.JLabel();
        PanelMenuLaporan = new javax.swing.JPanel();
        LabelIDLaporan = new javax.swing.JLabel();
        LabelLokasiJalan = new javax.swing.JLabel();
        LabelDiameter = new javax.swing.JLabel();
        LabelKedalaman = new javax.swing.JLabel();
        FotoLubangLabel = new javax.swing.JLabel();
        TextFieldIDLaporan = new javax.swing.JTextField();
        TextFieldDiameter = new javax.swing.JTextField();
        TextFieldKedalaman = new javax.swing.JTextField();
        TextFieldFotoLubang = new javax.swing.JTextField();
        ButtonBrowse = new javax.swing.JButton();
        ButtonUpload = new javax.swing.JButton();
        ButtonKembali = new javax.swing.JButton();
        ButtonSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaLokasiJalan = new javax.swing.JTextArea();
        panelGambar1 = new Views.PanelGambar();
        LabelNamaPelapor = new javax.swing.JLabel();
        TextFieldNamaPelapor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TextFieldTanggal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableLaporan = new javax.swing.JTable();

        javax.swing.GroupLayout panelGambar2Layout = new javax.swing.GroupLayout(panelGambar2);
        panelGambar2.setLayout(panelGambar2Layout);
        panelGambar2Layout.setHorizontalGroup(
            panelGambar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelGambar2Layout.setVerticalGroup(
            panelGambar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelKerusakanJalan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelJudul.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        LabelJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJudul.setText("Laporan Kerusakan Jalan");

        PanelMenuLaporan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelIDLaporan.setText("ID Laporan");

        LabelLokasiJalan.setText("Lokasi Jalan");

        LabelDiameter.setText("Diameter");

        LabelKedalaman.setText("Kedalaman");

        FotoLubangLabel.setText("Foto Lubang");

        ButtonBrowse.setText("Browse");
        ButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBrowseActionPerformed(evt);
            }
        });

        ButtonUpload.setText("Upload");

        ButtonKembali.setText("Kembali");

        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });

        TextAreaLokasiJalan.setColumns(20);
        TextAreaLokasiJalan.setRows(5);
        jScrollPane1.setViewportView(TextAreaLokasiJalan);

        panelGambar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelGambar1Layout = new javax.swing.GroupLayout(panelGambar1);
        panelGambar1.setLayout(panelGambar1Layout);
        panelGambar1Layout.setHorizontalGroup(
            panelGambar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelGambar1Layout.setVerticalGroup(
            panelGambar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        LabelNamaPelapor.setText("Nama Pelapor");

        jLabel1.setText("Tanggal");

        javax.swing.GroupLayout PanelMenuLaporanLayout = new javax.swing.GroupLayout(PanelMenuLaporan);
        PanelMenuLaporan.setLayout(PanelMenuLaporanLayout);
        PanelMenuLaporanLayout.setHorizontalGroup(
            PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLaporanLayout.createSequentialGroup()
                        .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelIDLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelNamaPelapor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldNamaPelapor)
                            .addComponent(TextFieldIDLaporan)))
                    .addGroup(PanelMenuLaporanLayout.createSequentialGroup()
                        .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LabelLokasiJalan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelDiameter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelKedalaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FotoLubangLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldDiameter)
                            .addComponent(TextFieldKedalaman)
                            .addComponent(TextFieldFotoLubang)
                            .addComponent(jScrollPane1)
                            .addGroup(PanelMenuLaporanLayout.createSequentialGroup()
                                .addComponent(ButtonKembali)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonSimpan))
                            .addGroup(PanelMenuLaporanLayout.createSequentialGroup()
                                .addComponent(panelGambar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonBrowse)
                                    .addComponent(ButtonUpload))
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addComponent(TextFieldTanggal))))
                .addContainerGap())
        );
        PanelMenuLaporanLayout.setVerticalGroup(
            PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIDLaporan)
                    .addComponent(TextFieldIDLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNamaPelapor)
                    .addComponent(TextFieldNamaPelapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLaporanLayout.createSequentialGroup()
                        .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TextFieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelLokasiJalan)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelDiameter)
                            .addComponent(TextFieldDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelKedalaman)
                            .addComponent(TextFieldKedalaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FotoLubangLabel)
                            .addComponent(TextFieldFotoLubang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMenuLaporanLayout.createSequentialGroup()
                                .addComponent(ButtonBrowse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonUpload))
                            .addComponent(panelGambar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLaporanLayout.createSequentialGroup()
                        .addGroup(PanelMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonKembali)
                            .addComponent(ButtonSimpan))
                        .addContainerGap())))
        );

        TableLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TableLaporan);

        javax.swing.GroupLayout PanelKerusakanJalanLayout = new javax.swing.GroupLayout(PanelKerusakanJalan);
        PanelKerusakanJalan.setLayout(PanelKerusakanJalanLayout);
        PanelKerusakanJalanLayout.setHorizontalGroup(
            PanelKerusakanJalanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKerusakanJalanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKerusakanJalanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelKerusakanJalanLayout.createSequentialGroup()
                        .addComponent(PanelMenuLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelKerusakanJalanLayout.setVerticalGroup(
            PanelKerusakanJalanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKerusakanJalanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelKerusakanJalanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelMenuLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelKerusakanJalanLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelKerusakanJalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelKerusakanJalan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
        String url;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/karyawan?zeroDateTimeBehavior=convertToNull";
            connect=DriverManager.getConnection(url,"root","");
            statemen=connect.prepareStatement("INSERT INTO laporan_pelapor(Laporan_ID, Nama_Pelapor, Tanggal_Laporan, Alamat_Lubang, Diameter, Kedalaman, Foto_Lubang) VALUES (?,?,?,?,?,?,?)");
            InputStream is = new FileInputStream(new File(s));
            statemen.setString(1, TextFieldIDLaporan.getText());
            statemen.setString(2, TextFieldNamaPelapor.getText());
            statemen.setString(3, TextFieldTanggal.getText());
            statemen.setString(4, TextAreaLokasiJalan.getText());
            statemen.setString(5, TextFieldDiameter.getText());
            statemen.setString(6, TextFieldKedalaman.getText());
            statemen.setBlob(7, is);
            statemen.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Anda sudah masuk didatabase");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Gagal, Pastiksn ID yang Anda Masukkan Belum Terdaftar dan Pastikan Database sudah terhubung.");
        }
    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void ButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBrowseActionPerformed
        JFileChooser pilih = new JFileChooser();
        pilih.setCurrentDirectory(new File(System.getProperty("user.home")));
        pilih.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image", "jpg","png","bmp");
        pilih.addChoosableFileFilter(filter);
        int hasil=pilih.showOpenDialog(null);
        if(hasil==JFileChooser.APPROVE_OPTION){
            File file=pilih.getSelectedFile();
            String path = file.getAbsolutePath();
            s=path;
            try {
                image = ImageIO.read(file);
                panelGambar1.setImage(image);
            } catch (IOException ex) {
                Logger.getLogger(FrameLaporan.class.getName()).log(Level.SEVERE, null, ex);
            }
            TextFieldFotoLubang.setText(file.getAbsolutePath());
        }        
    }//GEN-LAST:event_ButtonBrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBrowse;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JButton ButtonUpload;
    private javax.swing.JLabel FotoLubangLabel;
    private javax.swing.JLabel LabelDiameter;
    private javax.swing.JLabel LabelIDLaporan;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelKedalaman;
    private javax.swing.JLabel LabelLokasiJalan;
    private javax.swing.JLabel LabelNamaPelapor;
    private javax.swing.JPanel PanelKerusakanJalan;
    private javax.swing.JPanel PanelMenuLaporan;
    private javax.swing.JTable TableLaporan;
    private javax.swing.JTextArea TextAreaLokasiJalan;
    private javax.swing.JTextField TextFieldDiameter;
    private javax.swing.JTextField TextFieldFotoLubang;
    private javax.swing.JTextField TextFieldIDLaporan;
    private javax.swing.JTextField TextFieldKedalaman;
    private javax.swing.JTextField TextFieldNamaPelapor;
    private javax.swing.JTextField TextFieldTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private Views.PanelGambar panelGambar1;
    private Views.PanelGambar panelGambar2;
    // End of variables declaration//GEN-END:variables
   
}