/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Muhammad Asna Faqih
 */

// <editor-fold defaultstate="collapsed" desc="Import">
import java.sql.*;
import javax.swing.JOptionPane;
import Connection.ConnectionDB;
import Views.FrameLogin;
import javax.swing.table.DefaultTableModel;
// </editor-fold>

public class FrameRegister extends javax.swing.JFrame {

    /**
     * Creates new form FrameRegister
     */
    
    // <editor-fold defaultstate="collapsed" desc="Deklarasi Kelas">
    public Connection connect;
    public Statement statemen;
    public ResultSet rss;
    public String sql1="";
    public String sql2="";
    public FrameLogin lgn;
    // </editor-fold>
    
    public FrameRegister() {
        initComponents();
        setTitle("Identitas Pelapor");
    }
    
    
    public void tampilData(){
        DefaultTableModel tabelTampil = new DefaultTableModel();
        tabelTampil.addColumn("User_ID");
        tabelTampil.addColumn("Nama_Lengkap");
        tabelTampil.addColumn("No_Identitas");
        tabelTampil.addColumn("Alamat");
        tabelTampil.addColumn("No_Telepon");
        tabelTampil.addColumn("Email");
        tabelTampil.addColumn("Password");
        try{
            String url;
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/aplikasi_phtrs?zeroDateTimeBehavior=convertToNull";
            connect=DriverManager.getConnection(url,"root","");
            sql2="SELECT * FROM register order by nobp asc";
            statemen=connect.createStatement();
            ResultSet rs= statemen.executeQuery(sql2);
            while(rs.next()){
                tabelTampil.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
            });
            }
            TableIdentitasPelapor.setModel(tabelTampil);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ada kesalahan");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRegister = new javax.swing.JPanel();
        LabelJudul = new javax.swing.JLabel();
        PanelMenuIdentitas = new javax.swing.JPanel();
        LabelNamaLengkap = new javax.swing.JLabel();
        LabelNoIdentitas = new javax.swing.JLabel();
        LabelAlamat = new javax.swing.JLabel();
        LabelNoTelepon = new javax.swing.JLabel();
        TextFieldNamaLengkap = new javax.swing.JTextField();
        TextFieldNoIdentitas = new javax.swing.JTextField();
        TextFieldNoTelepon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaAlamat = new javax.swing.JTextArea();
        ButtonSimpan = new javax.swing.JButton();
        ButtonKembali = new javax.swing.JButton();
        LabelUserID = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextFieldPassword = new javax.swing.JTextField();
        TextFieldEmail = new javax.swing.JTextField();
        TextFieldUserID = new javax.swing.JTextField();
        ButtonEdit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableIdentitasPelapor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelRegister.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelJudul.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelJudul.setText("Pendaftaran Identitas Pelapor");

        PanelMenuIdentitas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelNamaLengkap.setText("Nama Lengkap");

        LabelNoIdentitas.setText("No. Identitas");

        LabelAlamat.setText("Alamat");

        LabelNoTelepon.setText("No. Telepon");

        TextAreaAlamat.setColumns(20);
        TextAreaAlamat.setRows(5);
        jScrollPane1.setViewportView(TextAreaAlamat);

        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });

        ButtonKembali.setText("Kembali");
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        LabelUserID.setText("User ID");

        LabelEmail.setText("Email");

        jLabel1.setText("Password");

        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuIdentitasLayout = new javax.swing.GroupLayout(PanelMenuIdentitas);
        PanelMenuIdentitas.setLayout(PanelMenuIdentitasLayout);
        PanelMenuIdentitasLayout.setHorizontalGroup(
            PanelMenuIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuIdentitasLayout.createSequentialGroup()
                .addGroup(PanelMenuIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuIdentitasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelMenuIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelUserID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNamaLengkap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(LabelNoIdentitas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelAlamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNoTelepon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMenuIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldUserID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldNamaLengkap, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldNoIdentitas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldNoTelepon)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldPassword)))
                    .addGroup(PanelMenuIdentitasLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(ButtonKembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEdit)
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelMenuIdentitasLayout.setVerticalGroup(
            PanelMenuIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuIdentitasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMenuIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUserID)
                    .addComponent(TextFieldUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMenuIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNamaLengkap)
                    .addComponent(TextFieldNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMenuIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNoIdentitas)
                    .addComponent(TextFieldNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMenuIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAlamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMenuIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNoTelepon)
                    .addComponent(TextFieldNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMenuIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmail)
                    .addComponent(TextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMenuIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMenuIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonKembali)
                    .addComponent(ButtonSimpan)
                    .addComponent(ButtonEdit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableIdentitasPelapor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User_ID", "Nama_Lengkap", "No_Identitas", "Alamat", "No_Telepon", "Email", "Password"
            }
        ));
        TableIdentitasPelapor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableIdentitasPelaporMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableIdentitasPelapor);

        javax.swing.GroupLayout PanelRegisterLayout = new javax.swing.GroupLayout(PanelRegister);
        PanelRegister.setLayout(PanelRegisterLayout);
        PanelRegisterLayout.setHorizontalGroup(
            PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelRegisterLayout.createSequentialGroup()
                        .addComponent(PanelMenuIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelRegisterLayout.setVerticalGroup(
            PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelMenuIdentitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
        String url;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/karyawan?zeroDateTimeBehavior=convertToNull";
            connect=DriverManager.getConnection(url,"root","");
            sql1 = "insert into register values('"+TextFieldUserID.getText()+"',"
                                           + "'"+TextFieldNamaLengkap.getText()+"',"
                                           + "'"+TextFieldNoIdentitas.getText()+"',"
                                           + "'"+TextAreaAlamat.getText()+"',"
                                           + "'"+TextFieldNoTelepon.getText()+"',"
                                           + "'"+TextFieldEmail.getText()+"',"
                                           + "'"+TextFieldPassword.getText()+"')";
            statemen=connect.createStatement();
            statemen.execute(sql1);
            TextFieldUserID.setText("");
            TextFieldNamaLengkap.setText("");
            TextFieldNoIdentitas.setText("");
            TextAreaAlamat.setText("");
            TextFieldNoTelepon.setText("");
            TextFieldEmail.setText("");
            TextFieldPassword.setText("");
            JOptionPane.showMessageDialog(null,"Identitas Anda sudah terdaftar didatabase");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Gagal, Pastiksn ID yang Anda Masukkan Belum Terdaftar dan Pastikan Database sudah terhubung.");
        }
    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        lgn=new FrameLogin();
        lgn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        String url;
        try{
            DefaultTableModel model =(DefaultTableModel)TableIdentitasPelapor.getModel();
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/karyawan?zeroDateTimeBehavior=convertToNull";
            connect=DriverManager.getConnection(url,"root","");
            sql1 = "UPDATE INTO register VALUES('"+TextFieldUserID.getText()+"',"
                                           + "'"+TextFieldNamaLengkap.getText()+"',"
                                           + "'"+TextFieldNoIdentitas.getText()+"',"
                                           + "'"+TextAreaAlamat.getText()+"',"
                                           + "'"+TextFieldNoTelepon.getText()+"',"
                                           + "'"+TextFieldEmail.getText()+"',"
                                           + "'"+TextFieldPassword.getText()+"')";
            if(TableIdentitasPelapor.getSelectedRow() == -1){
                if(TableIdentitasPelapor.getRowCount() == 0){
                    JOptionPane.showMessageDialog(null,"Tabel masih kosong");
                }else{
                    JOptionPane.showMessageDialog(null,"Klik Tabel");
                }
            }else{
                statemen=connect.createStatement();
                statemen.execute(sql1);
                model.setValueAt(TextFieldUserID.getText(), TableIdentitasPelapor.getSelectedRow(), 0);
                model.setValueAt(TextFieldNamaLengkap.getText(), TableIdentitasPelapor.getSelectedRow(), 1);
                model.setValueAt(TextFieldNoIdentitas.getText(), TableIdentitasPelapor.getSelectedRow(), 2);
                model.setValueAt(TextAreaAlamat.getText(), TableIdentitasPelapor.getSelectedRow(), 3);
                model.setValueAt(TextFieldNoTelepon.getText(), TableIdentitasPelapor.getSelectedRow(), 4);
                model.setValueAt(TextFieldEmail.getText(), TableIdentitasPelapor.getSelectedRow(), 5);
                model.setValueAt(TextFieldPassword.getText(), TableIdentitasPelapor.getSelectedRow(), 6);
                JOptionPane.showMessageDialog(null,"Identitas Anda sudah terdaftar didatabase");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Gagal, Pastiksn ID yang Anda Masukkan Belum Terdaftar dan Pastikan Database sudah terhubung.");
        }
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void TableIdentitasPelaporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableIdentitasPelaporMouseClicked
            DefaultTableModel model =(DefaultTableModel)TableIdentitasPelapor.getModel();
            TextFieldUserID.setText(model.getValueAt(TableIdentitasPelapor.getSelectedRow(), 0).toString());
            TextFieldNamaLengkap.setText(model.getValueAt(TableIdentitasPelapor.getSelectedRow(), 1).toString());
            TextFieldNoIdentitas.setText(model.getValueAt(TableIdentitasPelapor.getSelectedRow(), 2).toString());
            TextAreaAlamat.setText(model.getValueAt(TableIdentitasPelapor.getSelectedRow(), 3).toString());
            TextFieldNoTelepon.setText(model.getValueAt(TableIdentitasPelapor.getSelectedRow(), 4).toString());
            TextFieldEmail.setText(model.getValueAt(TableIdentitasPelapor.getSelectedRow(), 5).toString());
            TextFieldPassword.setText(model.getValueAt(TableIdentitasPelapor.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_TableIdentitasPelaporMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JLabel LabelAlamat;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelNamaLengkap;
    private javax.swing.JLabel LabelNoIdentitas;
    private javax.swing.JLabel LabelNoTelepon;
    private javax.swing.JLabel LabelUserID;
    private javax.swing.JPanel PanelMenuIdentitas;
    private javax.swing.JPanel PanelRegister;
    private javax.swing.JTable TableIdentitasPelapor;
    private javax.swing.JTextArea TextAreaAlamat;
    private javax.swing.JTextField TextFieldEmail;
    private javax.swing.JTextField TextFieldNamaLengkap;
    private javax.swing.JTextField TextFieldNoIdentitas;
    private javax.swing.JTextField TextFieldNoTelepon;
    private javax.swing.JTextField TextFieldPassword;
    private javax.swing.JTextField TextFieldUserID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
