/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Muhammad Asna Faqih
 */
public class FrameBerkasLaporan extends javax.swing.JFrame {

    /**
     * Creates new form FrameBerkasLaporan
     */
    
    // <editor-fold defaultstate="collapsed" desc="Deklarasi Kelas">
    public Connection connect;
    public PreparedStatement statemen = null;
    public ResultSet rss;
    public String sql="";
    public FrameLogin lgn;
    public String s;
    public String t;
    public String filename = null;
    public Image image;
    public FrameMenuAdmin mAdmin;
    // </editor-fold>
    public FrameBerkasLaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBerkas = new javax.swing.JPanel();
        PanelMenuBerkas = new javax.swing.JPanel();
        LabelIDLaporan = new javax.swing.JLabel();
        LabelNamaLaporan = new javax.swing.JLabel();
        LabelTanggalLaporan = new javax.swing.JLabel();
        LabelLokasiJalan = new javax.swing.JLabel();
        TextFieldIDLaporan = new javax.swing.JTextField();
        TextFieldNamaPelapor = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextAreaLokasiJalan = new javax.swing.JTextArea();
        LabelDiameter = new javax.swing.JLabel();
        LabelKedalaman = new javax.swing.JLabel();
        LabelFotoSebelum = new javax.swing.JLabel();
        PanelFotoSebelum = new javax.swing.JPanel();
        panelGambar1 = new Views.PanelGambar();
        LabelProgres = new javax.swing.JLabel();
        LabelFotoSesudah = new javax.swing.JLabel();
        TextFieldFotoSebelum = new javax.swing.JTextField();
        ComboBoxProgres = new javax.swing.JComboBox();
        PanelFotoSesudah = new javax.swing.JPanel();
        panelGambar2 = new Views.PanelGambar();
        ButtonKembali = new javax.swing.JButton();
        TextFieldDiameter = new javax.swing.JTextField();
        TextFieldKedalaman = new javax.swing.JTextField();
        TextFieldFotoSesudah = new javax.swing.JTextField();
        ButtonBrowse = new javax.swing.JButton();
        ButtonUpload = new javax.swing.JButton();
        ButtonBrowse2 = new javax.swing.JButton();
        ButtonUpload2 = new javax.swing.JButton();
        ButtonSimpan = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        ButtonLihatKaryawan = new javax.swing.JButton();
        ButtonLihatLaporan = new javax.swing.JButton();
        ButtonLihatPelapor = new javax.swing.JButton();
        LabelBerkasLaporan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBerkas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        PanelMenuBerkas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LabelIDLaporan.setText("ID Laporan");

        LabelNamaLaporan.setText("Nama Pelapor");

        LabelTanggalLaporan.setText("Tanggal Pelaporan");

        LabelLokasiJalan.setText("Lokasi Jalan");

        TextAreaLokasiJalan.setColumns(20);
        TextAreaLokasiJalan.setRows(5);
        jScrollPane4.setViewportView(TextAreaLokasiJalan);

        LabelDiameter.setText("Diameter");

        LabelKedalaman.setText("Kedalaman");

        LabelFotoSebelum.setText("Foto Lubang Sebelum diperbaiki  ");

        PanelFotoSebelum.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelGambar1Layout = new javax.swing.GroupLayout(panelGambar1);
        panelGambar1.setLayout(panelGambar1Layout);
        panelGambar1Layout.setHorizontalGroup(
            panelGambar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelGambar1Layout.setVerticalGroup(
            panelGambar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelFotoSebelumLayout = new javax.swing.GroupLayout(PanelFotoSebelum);
        PanelFotoSebelum.setLayout(PanelFotoSebelumLayout);
        PanelFotoSebelumLayout.setHorizontalGroup(
            PanelFotoSebelumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFotoSebelumLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelGambar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelFotoSebelumLayout.setVerticalGroup(
            PanelFotoSebelumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFotoSebelumLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelGambar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LabelProgres.setText("Progres");

        LabelFotoSesudah.setText("Foto Lubang Setelah diperbaiki");

        TextFieldFotoSebelum.setEditable(false);

        ComboBoxProgres.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PanelFotoSesudah.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelGambar2Layout = new javax.swing.GroupLayout(panelGambar2);
        panelGambar2.setLayout(panelGambar2Layout);
        panelGambar2Layout.setHorizontalGroup(
            panelGambar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelGambar2Layout.setVerticalGroup(
            panelGambar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelFotoSesudahLayout = new javax.swing.GroupLayout(PanelFotoSesudah);
        PanelFotoSesudah.setLayout(PanelFotoSesudahLayout);
        PanelFotoSesudahLayout.setHorizontalGroup(
            PanelFotoSesudahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFotoSesudahLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelGambar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelFotoSesudahLayout.setVerticalGroup(
            PanelFotoSesudahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFotoSesudahLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelGambar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ButtonKembali.setText("Kembali");
        ButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliActionPerformed(evt);
            }
        });

        TextFieldFotoSesudah.setEditable(false);

        ButtonBrowse.setText("Browse");
        ButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBrowseActionPerformed(evt);
            }
        });

        ButtonUpload.setText("Upload");

        ButtonBrowse2.setText("Browse");
        ButtonBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBrowse2ActionPerformed(evt);
            }
        });

        ButtonUpload2.setText("Upload");

        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });

        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        ButtonLihatKaryawan.setText("Lihat Data Karyawan");

        ButtonLihatLaporan.setText("Lihat Data Laporan");

        ButtonLihatPelapor.setText("Lihat Data Pelapor");

        javax.swing.GroupLayout PanelMenuBerkasLayout = new javax.swing.GroupLayout(PanelMenuBerkas);
        PanelMenuBerkas.setLayout(PanelMenuBerkasLayout);
        PanelMenuBerkasLayout.setHorizontalGroup(
            PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                        .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                                .addComponent(ButtonBrowse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonUpload))
                            .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                                .addComponent(ButtonLihatKaryawan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonLihatLaporan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonLihatPelapor)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                        .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                                .addComponent(LabelProgres, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldKedalaman)
                                    .addComponent(ComboBoxProgres, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                                .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                                        .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuBerkasLayout.createSequentialGroup()
                                                .addComponent(PanelFotoSebelum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53))
                                            .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(LabelFotoSebelum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TextFieldFotoSebelum, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                        .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(LabelFotoSesudah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TextFieldFotoSesudah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(PanelFotoSesudah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                                                .addComponent(ButtonBrowse2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ButtonUpload2)))
                                        .addGap(4, 4, 4))
                                    .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                                        .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(LabelKedalaman, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LabelDiameter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(LabelIDLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(LabelNamaLaporan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(LabelTanggalLaporan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(LabelLokasiJalan)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TextFieldNamaPelapor, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextFieldIDLaporan, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextFieldDiameter, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(ButtonKembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonHapus)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelMenuBerkasLayout.setVerticalGroup(
            PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIDLaporan)
                    .addComponent(TextFieldIDLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNamaLaporan)
                    .addComponent(TextFieldNamaPelapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTanggalLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                        .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelLokasiJalan)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelDiameter)
                            .addComponent(TextFieldDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelKedalaman)
                            .addComponent(TextFieldKedalaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelProgres)
                            .addComponent(ComboBoxProgres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelFotoSebelum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldFotoSebelum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelFotoSebelum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonBrowse)
                            .addComponent(ButtonUpload)))
                    .addGroup(PanelMenuBerkasLayout.createSequentialGroup()
                        .addComponent(LabelFotoSesudah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldFotoSesudah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelFotoSesudah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonBrowse2)
                            .addComponent(ButtonUpload2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonLihatKaryawan)
                    .addComponent(ButtonLihatLaporan)
                    .addComponent(ButtonLihatPelapor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelMenuBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonKembali)
                    .addComponent(ButtonSimpan)
                    .addComponent(ButtonEdit)
                    .addComponent(ButtonHapus))
                .addContainerGap())
        );

        LabelBerkasLaporan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelBerkasLaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBerkasLaporan.setText("Berkas Laporan Lubang Jalan");

        javax.swing.GroupLayout PanelBerkasLayout = new javax.swing.GroupLayout(PanelBerkas);
        PanelBerkas.setLayout(PanelBerkasLayout);
        PanelBerkasLayout.setHorizontalGroup(
            PanelBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBerkasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelBerkasLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelMenuBerkas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelBerkasLayout.setVerticalGroup(
            PanelBerkasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBerkasLayout.createSequentialGroup()
                .addComponent(LabelBerkasLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelMenuBerkas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBerkas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBerkas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliActionPerformed
        mAdmin = new FrameMenuAdmin();
        mAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonKembaliActionPerformed

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
        String url;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/karyawan?zeroDateTimeBehavior=convertToNull";
            connect=DriverManager.getConnection(url,"root","");
            statemen=connect.prepareStatement("INSERT INTO laporan pelapor(Laporan_ID, Nama_Pelapor, Alamat_Lubang, Diameter, Kedalaman, Foto_Lubang) VALUES (?,?,?,?,?,?,?)");
            InputStream is1 = new FileInputStream(new File(s));
            InputStream is2 = new FileInputStream(new File(t));
            statemen.setString(1, TextFieldIDLaporan.getText());
            statemen.setString(2, TextFieldKedalaman.getText());
            statemen.setString(3, TextAreaLokasiJalan.getText());
            statemen.setString(4, TextFieldDiameter.getText());
            statemen.setString(5, TextFieldKedalaman.getText());
            statemen.setString(6, TextFieldKedalaman.getText());
            statemen.setBlob(7, is1);
            statemen.setBlob(8, is2);
            statemen.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Anda sudah masuk didatabase");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Gagal, Pastiksn ID yang Anda Masukkan Belum Terdaftar dan Pastikan Database sudah terhubung.");
        }
    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void ButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBrowseActionPerformed
        JFileChooser pilih = new JFileChooser();
        pilih.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image", "jpg","png","bmp");
        pilih.addChoosableFileFilter(filter);
        if(pilih.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            File file=pilih.getSelectedFile();
            try {
                image = ImageIO.read(file);
                panelGambar1.setImage(image);
            } catch (IOException ex) {
                Logger.getLogger(FrameLaporan.class.getName()).log(Level.SEVERE, null, ex);
            }
            TextFieldFotoSebelum.setText(file.getAbsolutePath());
            s = file.getAbsolutePath();
        }
    }//GEN-LAST:event_ButtonBrowseActionPerformed

    private void ButtonBrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBrowse2ActionPerformed
        JFileChooser pilih = new JFileChooser();
        pilih.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Image", "jpg","png","bmp");
        pilih.addChoosableFileFilter(filter);
        if(pilih.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            File file=pilih.getSelectedFile();
            try {
                image = ImageIO.read(file);
                panelGambar2.setImage(image);
            } catch (IOException ex) {
                Logger.getLogger(FrameLaporan.class.getName()).log(Level.SEVERE, null, ex);
            }
            TextFieldFotoSesudah.setText(file.getAbsolutePath());
            s = file.getAbsolutePath();
        }
    }//GEN-LAST:event_ButtonBrowse2ActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBerkasLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBerkasLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBerkasLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBerkasLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBerkasLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBrowse;
    private javax.swing.JButton ButtonBrowse2;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonKembali;
    private javax.swing.JButton ButtonLihatKaryawan;
    private javax.swing.JButton ButtonLihatLaporan;
    private javax.swing.JButton ButtonLihatPelapor;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JButton ButtonUpload;
    private javax.swing.JButton ButtonUpload2;
    private javax.swing.JComboBox ComboBoxProgres;
    private javax.swing.JLabel LabelBerkasLaporan;
    private javax.swing.JLabel LabelDiameter;
    private javax.swing.JLabel LabelFotoSebelum;
    private javax.swing.JLabel LabelFotoSesudah;
    private javax.swing.JLabel LabelIDLaporan;
    private javax.swing.JLabel LabelKedalaman;
    private javax.swing.JLabel LabelLokasiJalan;
    private javax.swing.JLabel LabelNamaLaporan;
    private javax.swing.JLabel LabelProgres;
    private javax.swing.JLabel LabelTanggalLaporan;
    private javax.swing.JPanel PanelBerkas;
    private javax.swing.JPanel PanelFotoSebelum;
    private javax.swing.JPanel PanelFotoSesudah;
    private javax.swing.JPanel PanelMenuBerkas;
    private javax.swing.JTextArea TextAreaLokasiJalan;
    private javax.swing.JTextField TextFieldDiameter;
    private javax.swing.JTextField TextFieldFotoSebelum;
    private javax.swing.JTextField TextFieldFotoSesudah;
    private javax.swing.JTextField TextFieldIDLaporan;
    private javax.swing.JTextField TextFieldKedalaman;
    private javax.swing.JTextField TextFieldNamaPelapor;
    private javax.swing.JScrollPane jScrollPane4;
    private Views.PanelGambar panelGambar1;
    private Views.PanelGambar panelGambar2;
    // End of variables declaration//GEN-END:variables
}
